name: Developer_Branch_CI
on:
 push:
  tags:
    - "v*"
jobs:
 check-bat-version:
   runs-on: self-hosted
   steps:
     - name: Checkout
       uses: actions/checkout@v4
     - run: ls
     - run: tail index.js